export const GET_VIDEO_LIST = "GET_VIDEO_LIST"
export const LOADER = "LOADER"
export const CATEGORY = "CATEGORY"
export const GET_VIDEO = "GET_VIDEO"

export const GET_LIKED_VIDEOS = "GET_LIKED_VIDEOS"
export const ADD_TO_LIKED_VIDEOS = "ADD_TO_LIKED_VIDEOS"
export const DELETE_FROM_LIKED_VIDEOS = "DELETE_FROM_LIKED_VIDEOS"

export const RESET_DATA = "RESET_DATA"

export const SEARCH_VIDEO = "SEARCH_VIDEO"