export const GET_WATCHLATER_VIDEOS = "GET_WATCHLATER_VIDEOS"
export const ADD_TO_WATCHLATER_VIDEOS = "ADD_TO_WATCHLATER_VIDEOS"
export const REMOVE_FROM_WATCHLATER_VIDEOS = "REMOVE_FROM_WATCHLATER_VIDEOS"